{% set name = "pycustomfocus" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyCustomFocus-{{ version }}.tar.gz
  sha256: 3d4d6131f23d4baf3b9ffa7ba93512de7a7334a379e19bb6848d441ac69cd5e9
  patches:
    - qtpy.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - config
    - configparser
    - matplotlib-base
    - numpy
    - pydantic
    # - pyqt  # Replaced by qtpy with patch
    - pyqtgraph
    - python >=3.6
    - qdarkstyle
    - qtpy
    - scipy
    - tqdm

test:
  imports:
    - PyFocus
    - PyFocus.custom_dataclasses
    - PyFocus.custom_typing
    - PyFocus.equations
    - PyFocus.model
    - PyFocus.napari_adapter
    - PyFocus.plot_functions
    - PyFocus.user_interface
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/PyCustomFocus
  summary: Full vectorial calculation of focused electromagnetic fields moduled by a custom phase mask
  license: MIT
  license_file: LICENCE.txt
  dev_url: https://github.com/fcaprile/PyFocus

extra:
  recipe-maintainers:
    - jaimergp
    - goanpeca
